### ISSUE TITLE
Login Probleme bei Kickbase Login

### ISSUE THREAD

**Issue by Stiffler183** [phenze/kickbase-calculator#5]
Hallo Pascal, 
vorab erstmal vielen Dank für Deine großartige Arbeit mit dem Kickbase Calculator. Das Tool ist wirklich fester Bestandteil meiner Kickbase-Strategie und hilft sehr als Manager. Seit kurzem funktioniert allerdings der Kickbase Login nicht mehr. Trotz richtiger Kickbase Login-Daten erscheint die Meldung "Auf pascalhenze.de wird Folgendes angezeigt: Bitte Username und Password angeben". Eine Änderung des Passworts oder Wechseln des Endgeräts hat nicht geholfen. Gibt es Probleme mit der API? Wäre klasse, wenn du dir das Problem anschauen könntest. Vielen Dank vorab und beste Grüße an Dich!

**Comment by Komo92** [comment]
Ich erhalte eine 404, wenn ich den Login-Endpunkt direkt mit Postman aufrufe. Entweder hat Kickbase die API gestoppt oder es gibt Probleme.

**Comment by phenze** [comment]
Ich kümmere mich asap drum. Denke bis heute abend oder spät morgen bekomme ich das gelöst.

Die Api hat sich geändert ja.

Nachzulesen hier:

https://github.com/kevinskyba/kickbase-api-doc/issues/2

Wenn jemand entwickeln kann bitte gerne einen Pull Request stellen

**Comment by Komo92** [comment]
Ich denke der Login funktioniert jetzt über https://api.kickbase.com/v4/user/login? Könntest du mit mir den Body teilen wenn ich mit E-Mail und PW mich anmelden möchte? Danke für deine Hilfe

**Comment by phenze** [comment]
{
    "email": "",
    "password": ""
}

**Comment by laibold** [comment]
Auf https://api.kickbase.com/v4/user/login bekomme ich mit dem Body einen 401

**Comment by Komo92** [comment]
https://github.com/kevinskyba/kickbase-api-doc/issues/3#issuecomment-2462091165

**Comment by phenze** [comment]
Der Rechner funktioniert jetzt wieder

**Comment by Stiffler183** [comment]
> Der Rechner funktioniert jetzt wieder

@phenze Ein riesiges Dankeschön, Pascal! Danke, für deine Arbeit! ❤️

**Comment by laibold** [comment]
@t3mr0i Das Repo ist leider nicht public 😕

**Comment by casudo** [comment]
> @t3mr0i Das Repo ist leider nicht public 😕

Schau mal in diesem Repo hier:

https://github.com/simonsagstetter/kickbase-api-v4-docs

**Comment by t3mr0i** [comment]
Ja genau :) Hab gesehen, dass ihr das Projekt von meinem Kollegen nun als Maintainer übernommen habt. Damit wir als Community nun keine Verwirrung haben durch viele verschiedene Repos, habe ich meines erstmal auf private gestellt. :) 
Sollte irgendwann mal eines der Repos abgeschaltet wird, würde ich meines wieder auf "öffentlich" stellen.
